Exception: avoid exceptions when created exceptions.
Fix issue #3493.

	* share/urbi/exception.u (Type): Use getSlot to avoid firing
	primitives for instance.
	* tests: Update to check this.